### ISSUE TITLE
在IDE运行时`import easyquotation`报错

### ISSUE THREAD

**Issue by LiCarry** [shidenggui/easyquotation#105]
以下是报错内容：
Traceback (most recent call last):
  File "C:\Users\XXX\Desktop\Stock\main.py", line 7, in <module>
    import easyquotation
  File "C:\Users\XXX\Desktop\Stock\venv\lib\site-packages\easyquotation\__init__.py", line 2, in <module>
    from .api import *
  File "C:\Users\XXX\Desktop\Stock\venv\lib\site-packages\easyquotation\api.py", line 3, in <module>
    from . import boc, daykline, hkquote, jsl, sina, tencent, timekline
  File "C:\Users\XXX\Desktop\Stock\venv\lib\site-packages\easyquotation\boc.py", line 4, in <module>
    import requests
  File "C:\Users\XXX\Desktop\Stock\venv\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\XXX\Desktop\Stock\venv\lib\site-packages\urllib3\__init__.py", line 13, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "C:\Users\XXX\Desktop\Stock\venv\lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .connection import (
  File "C:\Users\XXX\Desktop\Stock\venv\lib\site-packages\urllib3\connection.py", line 54, in <module>
    from .packages.ssl_match_hostname import CertificateError, match_hostname
ImportError: cannot import name 'CertificateError' from 'urllib3.packages.ssl_match_hostname' (unknown location)

**Comment by shidenggui** [comment]
这个是 requests 问题
