### ISSUE TITLE
exception received

### ISSUE THREAD

**Issue by ewensun** [shidenggui/easyquotation#12]
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Python35\lib\asyncio\selector_events.py", line 664, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\aiohttp\client.py", line 187, in _request
    yield from resp.start(conn, read_until_eof)
  File "C:\Python35\lib\site-packages\aiohttp\client_reqrep.py", line 606, in start
    message = yield from httpstream.read()
  File "C:\Python35\lib\site-packages\aiohttp\streams.py", line 591, in read
    result = yield from super().read()
  File "C:\Python35\lib\site-packages\aiohttp\streams.py", line 446, in read
    yield from self._waiter
  File "C:\Python35\lib\asyncio\futures.py", line 358, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Python35\lib\asyncio\tasks.py", line 290, in _wakeup
    future.result()
  File "C:\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python35\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Python35\lib\threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "C:\wenjie\workspace\playAll\myEasyTrader\easyquant\push_engine\base_engine.py", line 30, in push_quotation
    response_data = self.fetch_quotation()
  File "C:\wenjie\workspace\playAll\myEasyTrader\easyquant\push_engine\quotation_engine.py", line 16, in fetch_quotation
    return self.source.all
  File "C:\wenjie\workspace\playAll\myEasyTrader\easyquotation\basequotation.py", line 38, in all
    return self.get_stock_data(self.stock_list)
  File "C:\wenjie\workspace\playAll\myEasyTrader\easyquotation\basequotation.py", line 62, in get_stock_data
    res = loop.run_until_complete(asyncio.gather(*coroutines))
  File "C:\Python35\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "C:\Python35\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Python35\lib\asyncio\tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "C:\wenjie\workspace\playAll\myEasyTrader\easyquotation\basequotation.py", line 48, in get_stocks_by_range
    async with aiohttp.get(self.stock_api + params) as r:
  File "C:\Python35\lib\site-packages\aiohttp\client.py", line 538, in __aenter__
    self._resp = yield from self._coro
  File "C:\Python35\lib\site-packages\aiohttp\client.py", line 194, in _request
    raise aiohttp.ClientResponseError() from exc
aiohttp.errors.ClientResponseError

**Comment by shidenggui** [comment]
如果请求太频繁了或者新浪那边出错的话就会出现这个错误。可能后面要加个更加友好的提示
