### ISSUE TITLE
获取数据超时

### ISSUE THREAD

**Issue by asxzy** [shidenggui/easyquotation#19]
对获取超时没有做异常处理，网络不稳定的情况下会抛出exception。
```
Traceback (most recent call last):
  File "crawler.py", line 16, in <module>
    data = quotation.all
  File "/usr/local/lib/python3.5/site-packages/easyquotation/basequotation.py", line 39, in all
    return self.get_stock_data(self.stock_list)
  File "/usr/local/lib/python3.5/site-packages/easyquotation/basequotation.py", line 68, in get_stock_data
    res = loop.run_until_complete(asyncio.gather(*coroutines))
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/site-packages/easyquotation/basequotation.py", line 52, in get_stocks_by_range
    async with self._session.get(self.stock_api + params, timeout=0.1, headers=headers) as r:
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 565, in __aenter__
    self._resp = yield from self._coro
  File "/usr/local/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/site-packages/async_timeout/__init__.py", line 44, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10de2d9b0>
```

**Comment by asxzy** [comment]
已尝试在代码里加入判断，一会儿我发个
