### ISSUE TITLE
获取港股信息出现错误

### ISSUE THREAD

**Issue by AlexZhou1995** [shidenggui/easyquotation#41]
按照Readme.md中最后一部分，获取腾讯股票的信息，结果报错

```
>>> import easyquotation
>>> quotation = easyquotation.use("hkquote")
>>> data = quotation.get_stock_data(stock_list=['00001','00700'])
('00700',)
http://sqt.gtimg.cn/utf8/q=r_hk00700
('00001',)
http://sqt.gtimg.cn/utf8/q=r_hk00001
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\easyquotation\hkqoute.py", line 90, in get_stock_data
    res = loop.run_until_complete(asyncio.gather(*coroutines))
  File "C:\Anaconda3\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Anaconda3\lib\asyncio\futures.py", line 294, in result
    raise self._exception
  File "C:\Anaconda3\lib\asyncio\tasks.py", line 240, in _step
    result = coro.send(None)
  File "C:\Anaconda3\lib\site-packages\easyquotation\hkqoute.py", line 72, in get_stocks_by_range
    async with self._session.get(url, timeout=10, headers=headers) as r:
AttributeError: __aexit__
```

**Comment by ljcljc** [comment]
请问这个问题修复了吗，我也遇到这个问题了

**Comment by shidenggui** [comment]
已经修复了，请使用新接口 `quotation.real(['00001','00700'])`

**Comment by wsm1992** [comment]
@shidenggui 
在獲取港股K線時,使用easyquotation.use("daykline")也有同樣的問題,請幫忙修復,謝謝
